### ISSUE TITLE
The API "/users/{id}/interests/{value}" will cause documents damage.

### ISSUE THREAD

**Issue by qiuyujx** [mapr-demos/maprdb-ojai-rest-sample#2]
@tgrall Thanks a lot providing such good examples. I just found some small issues in this repo.

I tried to add interests to a user via http://localhost:8080/swagger/#!/users/addInderest.
It is fine if only one term is added. However, if multiple are added, the user document will be damage that cannot be read any more.
Specifically, the POST query will succeed, but when retrieve the document afterwards, it throws ArrayIndexOutOfBoundsException as below
```
4883449 [qtp432906235-55] WARN org.eclipse.jetty.servlet.ServletHandler -
javax.servlet.ServletException: java.lang.ArrayIndexOutOfBoundsException: 3
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:392)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:219)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:681)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:449)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1084)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:376)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1018)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
        at com.mapr.db.rowcol.TimeDescriptor.deserialize(TimeDescriptor.java:228)
        at com.mapr.db.rowcol.KeyValueDeserializeHelper.deserializeWithoutKeyValue(KeyValueDeserializeHelper.java:51)
        at com.mapr.db.ojai.DBDocumentReader.getNextType(DBDocumentReader.java:411)
        at com.mapr.db.ojai.DBDocumentReader.dfsVisit(DBDocumentReader.java:249)
        at com.mapr.db.ojai.DBDocumentReader.next(DBDocumentReader.java:551)
        at org.ojai.util.MapEncoder.encodeArray(MapEncoder.java:114)
        at org.ojai.util.MapEncoder.encodeMap(MapEncoder.java:72)
        at org.ojai.util.MapEncoder.encode(MapEncoder.java:50)
        at com.mapr.db.rowcol.DBDocumentImpl.asMap(DBDocumentImpl.java:1653)
        at com.mapr.db.samples.rest.api.UserService.getusers(UserService.java:230)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:406)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:350)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:319)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
        ... 19 more
```

Some spelling mistakes in the source code:

In com.mapr.db.samples.rest.api.UserService:

A same comment "// The following code will udpate the user document and add/append an interest" appears in some unrelated methods.

The method name "addInderest()" has typos..

"udpate" has typo.

**Comment by qiuyujx** [comment]
Update interests via /users/from_string API works fine instead.
